# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13r-GtcjLo8vPT5MrT3UozV6QmQDOHMaI
"""

!pip install imdbpy

!pip install requests

!pip install selenium

import requests
from bs4 import BeautifulSoup

result = requests.get('https://en.wikipedia.org/wiki/List_of_Indian_film_actors')
html_page = result.content
soup = BeautifulSoup(html_page, 'html.parser')
text = soup.find_all(text=True)
output = ''
blacklist = [
	'[document]',
	'noscript',
	'header',
	'html',
	'meta',
	'head', 
	'input',
	'script',
]
for t in text:
	if t.parent.name not in blacklist:
		output += '{} '.format(t)

print(output)

f= open("list of actors.txt","w+")
for i in range(10):
     f.write(output)

actors = []
with open('/content/list of actors.txt') as t:
  for line in t:
    actors.append(line)
actors[5]

import imdb
ia = imdb.IMDb()

for name in actors:
  people = ia.search_person(name)
  for person in people:
    print(person.personID, person['name'])
    ids = person.personID
    name = person['name']
    break
  person = ia.get_person_biography(ids)
  break

person = ia.get_person_biography(ids)
print(person)